#!/bin/bash

RUN_SCRIPT=/people/turn652/GCAM/gcam-5/exe/run-gcam_shared.sh

sbatch -J wg_lo_rs_SSP1_hadg_2p6 $RUN_SCRIPT
sbatch -J gl_lo_rs_SSP1_hadg_2p6 $RUN_SCRIPT
sbatch -J wg_md_rs_SSP1_hadg_2p6 $RUN_SCRIPT
sbatch -J gl_md_rs_SSP1_hadg_2p6 $RUN_SCRIPT
sbatch -J wg_hi_rs_SSP1_hadg_2p6 $RUN_SCRIPT
sbatch -J gl_hi_rs_SSP1_hadg_2p6 $RUN_SCRIPT
sbatch -J wg_lo_rs_SSP2_hadg_2p6 $RUN_SCRIPT
sbatch -J gl_lo_rs_SSP2_hadg_2p6 $RUN_SCRIPT
sbatch -J wg_md_rs_SSP2_hadg_2p6 $RUN_SCRIPT
sbatch -J gl_md_rs_SSP2_hadg_2p6 $RUN_SCRIPT
sbatch -J wg_hi_rs_SSP2_hadg_2p6 $RUN_SCRIPT
sbatch -J gl_hi_rs_SSP2_hadg_2p6 $RUN_SCRIPT
sbatch -J wg_lo_rs_SSP4_hadg_2p6 $RUN_SCRIPT
sbatch -J gl_lo_rs_SSP4_hadg_2p6 $RUN_SCRIPT
sbatch -J wg_md_rs_SSP4_hadg_2p6 $RUN_SCRIPT
sbatch -J gl_md_rs_SSP4_hadg_2p6 $RUN_SCRIPT
sbatch -J wg_hi_rs_SSP4_hadg_2p6 $RUN_SCRIPT
sbatch -J gl_hi_rs_SSP4_hadg_2p6 $RUN_SCRIPT
sbatch -J wg_lo_rs_SSP5_hadg_2p6 $RUN_SCRIPT
sbatch -J gl_lo_rs_SSP5_hadg_2p6 $RUN_SCRIPT
sbatch -J wg_md_rs_SSP5_hadg_2p6 $RUN_SCRIPT
sbatch -J gl_md_rs_SSP5_hadg_2p6 $RUN_SCRIPT
sbatch -J wg_hi_rs_SSP5_hadg_2p6 $RUN_SCRIPT
sbatch -J gl_hi_rs_SSP5_hadg_2p6 $RUN_SCRIPT
sbatch -J wg_lo_rs_SSP1_miro_2p6 $RUN_SCRIPT
sbatch -J gl_lo_rs_SSP1_miro_2p6 $RUN_SCRIPT
sbatch -J wg_md_rs_SSP1_miro_2p6 $RUN_SCRIPT
sbatch -J gl_md_rs_SSP1_miro_2p6 $RUN_SCRIPT
sbatch -J wg_hi_rs_SSP1_miro_2p6 $RUN_SCRIPT
sbatch -J gl_hi_rs_SSP1_miro_2p6 $RUN_SCRIPT
sbatch -J wg_lo_rs_SSP2_miro_2p6 $RUN_SCRIPT
sbatch -J gl_lo_rs_SSP2_miro_2p6 $RUN_SCRIPT
sbatch -J wg_md_rs_SSP2_miro_2p6 $RUN_SCRIPT
sbatch -J gl_md_rs_SSP2_miro_2p6 $RUN_SCRIPT
sbatch -J wg_hi_rs_SSP2_miro_2p6 $RUN_SCRIPT
sbatch -J gl_hi_rs_SSP2_miro_2p6 $RUN_SCRIPT
sbatch -J wg_lo_rs_SSP4_miro_2p6 $RUN_SCRIPT
sbatch -J gl_lo_rs_SSP4_miro_2p6 $RUN_SCRIPT
sbatch -J wg_md_rs_SSP4_miro_2p6 $RUN_SCRIPT
sbatch -J gl_md_rs_SSP4_miro_2p6 $RUN_SCRIPT
sbatch -J wg_hi_rs_SSP4_miro_2p6 $RUN_SCRIPT
sbatch -J gl_hi_rs_SSP4_miro_2p6 $RUN_SCRIPT
sbatch -J wg_lo_rs_SSP5_miro_2p6 $RUN_SCRIPT
sbatch -J gl_lo_rs_SSP5_miro_2p6 $RUN_SCRIPT
sbatch -J wg_md_rs_SSP5_miro_2p6 $RUN_SCRIPT
sbatch -J gl_md_rs_SSP5_miro_2p6 $RUN_SCRIPT
sbatch -J wg_hi_rs_SSP5_miro_2p6 $RUN_SCRIPT
sbatch -J gl_hi_rs_SSP5_miro_2p6 $RUN_SCRIPT
sbatch -J wg_lo_rs_SSP1_nrsm_2p6 $RUN_SCRIPT
sbatch -J gl_lo_rs_SSP1_nrsm_2p6 $RUN_SCRIPT
sbatch -J wg_md_rs_SSP1_nrsm_2p6 $RUN_SCRIPT
sbatch -J gl_md_rs_SSP1_nrsm_2p6 $RUN_SCRIPT
sbatch -J wg_hi_rs_SSP1_nrsm_2p6 $RUN_SCRIPT
sbatch -J gl_hi_rs_SSP1_nrsm_2p6 $RUN_SCRIPT
sbatch -J wg_lo_rs_SSP2_nrsm_2p6 $RUN_SCRIPT
sbatch -J gl_lo_rs_SSP2_nrsm_2p6 $RUN_SCRIPT
sbatch -J wg_md_rs_SSP2_nrsm_2p6 $RUN_SCRIPT
sbatch -J gl_md_rs_SSP2_nrsm_2p6 $RUN_SCRIPT
sbatch -J wg_hi_rs_SSP2_nrsm_2p6 $RUN_SCRIPT
sbatch -J gl_hi_rs_SSP2_nrsm_2p6 $RUN_SCRIPT
sbatch -J wg_lo_rs_SSP4_nrsm_2p6 $RUN_SCRIPT
sbatch -J gl_lo_rs_SSP4_nrsm_2p6 $RUN_SCRIPT
sbatch -J wg_md_rs_SSP4_nrsm_2p6 $RUN_SCRIPT
sbatch -J gl_md_rs_SSP4_nrsm_2p6 $RUN_SCRIPT
sbatch -J wg_hi_rs_SSP4_nrsm_2p6 $RUN_SCRIPT
sbatch -J gl_hi_rs_SSP4_nrsm_2p6 $RUN_SCRIPT
sbatch -J wg_lo_rs_SSP5_nrsm_2p6 $RUN_SCRIPT
sbatch -J gl_lo_rs_SSP5_nrsm_2p6 $RUN_SCRIPT
sbatch -J wg_md_rs_SSP5_nrsm_2p6 $RUN_SCRIPT
sbatch -J gl_md_rs_SSP5_nrsm_2p6 $RUN_SCRIPT
sbatch -J wg_hi_rs_SSP5_nrsm_2p6 $RUN_SCRIPT
sbatch -J gl_hi_rs_SSP5_nrsm_2p6 $RUN_SCRIPT
sbatch -J wg_lo_rs_SSP1_hadg_4p5 $RUN_SCRIPT
sbatch -J gl_lo_rs_SSP1_hadg_4p5 $RUN_SCRIPT
sbatch -J wg_md_rs_SSP1_hadg_4p5 $RUN_SCRIPT
sbatch -J gl_md_rs_SSP1_hadg_4p5 $RUN_SCRIPT
sbatch -J wg_hi_rs_SSP1_hadg_4p5 $RUN_SCRIPT
sbatch -J gl_hi_rs_SSP1_hadg_4p5 $RUN_SCRIPT
sbatch -J wg_lo_rs_SSP2_hadg_4p5 $RUN_SCRIPT
sbatch -J gl_lo_rs_SSP2_hadg_4p5 $RUN_SCRIPT
sbatch -J wg_md_rs_SSP2_hadg_4p5 $RUN_SCRIPT
sbatch -J gl_md_rs_SSP2_hadg_4p5 $RUN_SCRIPT
sbatch -J wg_hi_rs_SSP2_hadg_4p5 $RUN_SCRIPT
sbatch -J gl_hi_rs_SSP2_hadg_4p5 $RUN_SCRIPT
sbatch -J wg_lo_rs_SSP3_hadg_4p5 $RUN_SCRIPT
sbatch -J gl_lo_rs_SSP3_hadg_4p5 $RUN_SCRIPT
sbatch -J wg_md_rs_SSP3_hadg_4p5 $RUN_SCRIPT
sbatch -J gl_md_rs_SSP3_hadg_4p5 $RUN_SCRIPT
sbatch -J wg_hi_rs_SSP3_hadg_4p5 $RUN_SCRIPT
sbatch -J gl_hi_rs_SSP3_hadg_4p5 $RUN_SCRIPT
sbatch -J wg_lo_rs_SSP4_hadg_4p5 $RUN_SCRIPT
sbatch -J gl_lo_rs_SSP4_hadg_4p5 $RUN_SCRIPT
sbatch -J wg_md_rs_SSP4_hadg_4p5 $RUN_SCRIPT
sbatch -J gl_md_rs_SSP4_hadg_4p5 $RUN_SCRIPT
sbatch -J wg_hi_rs_SSP4_hadg_4p5 $RUN_SCRIPT
sbatch -J gl_hi_rs_SSP4_hadg_4p5 $RUN_SCRIPT
sbatch -J wg_lo_rs_SSP5_hadg_4p5 $RUN_SCRIPT
sbatch -J gl_lo_rs_SSP5_hadg_4p5 $RUN_SCRIPT
sbatch -J wg_md_rs_SSP5_hadg_4p5 $RUN_SCRIPT
sbatch -J gl_md_rs_SSP5_hadg_4p5 $RUN_SCRIPT
sbatch -J wg_hi_rs_SSP5_hadg_4p5 $RUN_SCRIPT
sbatch -J gl_hi_rs_SSP5_hadg_4p5 $RUN_SCRIPT
sbatch -J wg_lo_rs_SSP1_miro_4p5 $RUN_SCRIPT
sbatch -J gl_lo_rs_SSP1_miro_4p5 $RUN_SCRIPT
sbatch -J wg_md_rs_SSP1_miro_4p5 $RUN_SCRIPT
sbatch -J gl_md_rs_SSP1_miro_4p5 $RUN_SCRIPT
sbatch -J wg_hi_rs_SSP1_miro_4p5 $RUN_SCRIPT
sbatch -J gl_hi_rs_SSP1_miro_4p5 $RUN_SCRIPT
sbatch -J wg_lo_rs_SSP2_miro_4p5 $RUN_SCRIPT
sbatch -J gl_lo_rs_SSP2_miro_4p5 $RUN_SCRIPT
sbatch -J wg_md_rs_SSP2_miro_4p5 $RUN_SCRIPT
sbatch -J gl_md_rs_SSP2_miro_4p5 $RUN_SCRIPT
sbatch -J wg_hi_rs_SSP2_miro_4p5 $RUN_SCRIPT
sbatch -J gl_hi_rs_SSP2_miro_4p5 $RUN_SCRIPT
sbatch -J wg_lo_rs_SSP3_miro_4p5 $RUN_SCRIPT
sbatch -J gl_lo_rs_SSP3_miro_4p5 $RUN_SCRIPT
sbatch -J wg_md_rs_SSP3_miro_4p5 $RUN_SCRIPT
sbatch -J gl_md_rs_SSP3_miro_4p5 $RUN_SCRIPT
sbatch -J wg_hi_rs_SSP3_miro_4p5 $RUN_SCRIPT
sbatch -J gl_hi_rs_SSP3_miro_4p5 $RUN_SCRIPT
sbatch -J wg_lo_rs_SSP4_miro_4p5 $RUN_SCRIPT
sbatch -J gl_lo_rs_SSP4_miro_4p5 $RUN_SCRIPT
sbatch -J wg_md_rs_SSP4_miro_4p5 $RUN_SCRIPT
sbatch -J gl_md_rs_SSP4_miro_4p5 $RUN_SCRIPT
sbatch -J wg_hi_rs_SSP4_miro_4p5 $RUN_SCRIPT
sbatch -J gl_hi_rs_SSP4_miro_4p5 $RUN_SCRIPT
sbatch -J wg_lo_rs_SSP5_miro_4p5 $RUN_SCRIPT
sbatch -J gl_lo_rs_SSP5_miro_4p5 $RUN_SCRIPT
sbatch -J wg_md_rs_SSP5_miro_4p5 $RUN_SCRIPT
sbatch -J gl_md_rs_SSP5_miro_4p5 $RUN_SCRIPT
sbatch -J wg_hi_rs_SSP5_miro_4p5 $RUN_SCRIPT
sbatch -J gl_hi_rs_SSP5_miro_4p5 $RUN_SCRIPT
sbatch -J wg_lo_rs_SSP1_nrsm_4p5 $RUN_SCRIPT
sbatch -J gl_lo_rs_SSP1_nrsm_4p5 $RUN_SCRIPT
sbatch -J wg_md_rs_SSP1_nrsm_4p5 $RUN_SCRIPT
sbatch -J gl_md_rs_SSP1_nrsm_4p5 $RUN_SCRIPT
sbatch -J wg_hi_rs_SSP1_nrsm_4p5 $RUN_SCRIPT
sbatch -J gl_hi_rs_SSP1_nrsm_4p5 $RUN_SCRIPT
sbatch -J wg_lo_rs_SSP2_nrsm_4p5 $RUN_SCRIPT
sbatch -J gl_lo_rs_SSP2_nrsm_4p5 $RUN_SCRIPT
sbatch -J wg_md_rs_SSP2_nrsm_4p5 $RUN_SCRIPT
sbatch -J gl_md_rs_SSP2_nrsm_4p5 $RUN_SCRIPT
sbatch -J wg_hi_rs_SSP2_nrsm_4p5 $RUN_SCRIPT
sbatch -J gl_hi_rs_SSP2_nrsm_4p5 $RUN_SCRIPT
sbatch -J wg_lo_rs_SSP3_nrsm_4p5 $RUN_SCRIPT
sbatch -J gl_lo_rs_SSP3_nrsm_4p5 $RUN_SCRIPT
sbatch -J wg_md_rs_SSP3_nrsm_4p5 $RUN_SCRIPT
sbatch -J gl_md_rs_SSP3_nrsm_4p5 $RUN_SCRIPT
sbatch -J wg_hi_rs_SSP3_nrsm_4p5 $RUN_SCRIPT
sbatch -J gl_hi_rs_SSP3_nrsm_4p5 $RUN_SCRIPT
sbatch -J wg_lo_rs_SSP4_nrsm_4p5 $RUN_SCRIPT
sbatch -J gl_lo_rs_SSP4_nrsm_4p5 $RUN_SCRIPT
sbatch -J wg_md_rs_SSP4_nrsm_4p5 $RUN_SCRIPT
sbatch -J gl_md_rs_SSP4_nrsm_4p5 $RUN_SCRIPT
sbatch -J wg_hi_rs_SSP4_nrsm_4p5 $RUN_SCRIPT
sbatch -J gl_hi_rs_SSP4_nrsm_4p5 $RUN_SCRIPT
sbatch -J wg_lo_rs_SSP5_nrsm_4p5 $RUN_SCRIPT
sbatch -J gl_lo_rs_SSP5_nrsm_4p5 $RUN_SCRIPT
sbatch -J wg_md_rs_SSP5_nrsm_4p5 $RUN_SCRIPT
sbatch -J gl_md_rs_SSP5_nrsm_4p5 $RUN_SCRIPT
sbatch -J wg_hi_rs_SSP5_nrsm_4p5 $RUN_SCRIPT
sbatch -J gl_hi_rs_SSP5_nrsm_4p5 $RUN_SCRIPT
sbatch -J wg_lo_rs_SSP1_hadg_6p0 $RUN_SCRIPT
sbatch -J gl_lo_rs_SSP1_hadg_6p0 $RUN_SCRIPT
sbatch -J wg_md_rs_SSP1_hadg_6p0 $RUN_SCRIPT
sbatch -J gl_md_rs_SSP1_hadg_6p0 $RUN_SCRIPT
sbatch -J wg_hi_rs_SSP1_hadg_6p0 $RUN_SCRIPT
sbatch -J gl_hi_rs_SSP1_hadg_6p0 $RUN_SCRIPT
sbatch -J wg_lo_rs_SSP2_hadg_6p0 $RUN_SCRIPT
sbatch -J gl_lo_rs_SSP2_hadg_6p0 $RUN_SCRIPT
sbatch -J wg_md_rs_SSP2_hadg_6p0 $RUN_SCRIPT
sbatch -J gl_md_rs_SSP2_hadg_6p0 $RUN_SCRIPT
sbatch -J wg_hi_rs_SSP2_hadg_6p0 $RUN_SCRIPT
sbatch -J gl_hi_rs_SSP2_hadg_6p0 $RUN_SCRIPT
sbatch -J wg_lo_rs_SSP3_hadg_6p0 $RUN_SCRIPT
sbatch -J gl_lo_rs_SSP3_hadg_6p0 $RUN_SCRIPT
sbatch -J wg_md_rs_SSP3_hadg_6p0 $RUN_SCRIPT
sbatch -J gl_md_rs_SSP3_hadg_6p0 $RUN_SCRIPT
sbatch -J wg_hi_rs_SSP3_hadg_6p0 $RUN_SCRIPT
sbatch -J gl_hi_rs_SSP3_hadg_6p0 $RUN_SCRIPT
sbatch -J wg_lo_rs_SSP4_hadg_6p0 $RUN_SCRIPT
sbatch -J gl_lo_rs_SSP4_hadg_6p0 $RUN_SCRIPT
sbatch -J wg_md_rs_SSP4_hadg_6p0 $RUN_SCRIPT
sbatch -J gl_md_rs_SSP4_hadg_6p0 $RUN_SCRIPT
sbatch -J wg_hi_rs_SSP4_hadg_6p0 $RUN_SCRIPT
sbatch -J gl_hi_rs_SSP4_hadg_6p0 $RUN_SCRIPT
sbatch -J wg_lo_rs_SSP5_hadg_6p0 $RUN_SCRIPT
sbatch -J gl_lo_rs_SSP5_hadg_6p0 $RUN_SCRIPT
sbatch -J wg_md_rs_SSP5_hadg_6p0 $RUN_SCRIPT
sbatch -J gl_md_rs_SSP5_hadg_6p0 $RUN_SCRIPT
sbatch -J wg_hi_rs_SSP5_hadg_6p0 $RUN_SCRIPT
sbatch -J gl_hi_rs_SSP5_hadg_6p0 $RUN_SCRIPT
sbatch -J wg_lo_rs_SSP1_miro_6p0 $RUN_SCRIPT
sbatch -J gl_lo_rs_SSP1_miro_6p0 $RUN_SCRIPT
sbatch -J wg_md_rs_SSP1_miro_6p0 $RUN_SCRIPT
sbatch -J gl_md_rs_SSP1_miro_6p0 $RUN_SCRIPT
sbatch -J wg_hi_rs_SSP1_miro_6p0 $RUN_SCRIPT
sbatch -J gl_hi_rs_SSP1_miro_6p0 $RUN_SCRIPT
sbatch -J wg_lo_rs_SSP2_miro_6p0 $RUN_SCRIPT
sbatch -J gl_lo_rs_SSP2_miro_6p0 $RUN_SCRIPT
sbatch -J wg_md_rs_SSP2_miro_6p0 $RUN_SCRIPT
sbatch -J gl_md_rs_SSP2_miro_6p0 $RUN_SCRIPT
sbatch -J wg_hi_rs_SSP2_miro_6p0 $RUN_SCRIPT
sbatch -J gl_hi_rs_SSP2_miro_6p0 $RUN_SCRIPT
sbatch -J wg_lo_rs_SSP3_miro_6p0 $RUN_SCRIPT
sbatch -J gl_lo_rs_SSP3_miro_6p0 $RUN_SCRIPT
sbatch -J wg_md_rs_SSP3_miro_6p0 $RUN_SCRIPT
sbatch -J gl_md_rs_SSP3_miro_6p0 $RUN_SCRIPT
sbatch -J wg_hi_rs_SSP3_miro_6p0 $RUN_SCRIPT
sbatch -J gl_hi_rs_SSP3_miro_6p0 $RUN_SCRIPT
sbatch -J wg_lo_rs_SSP4_miro_6p0 $RUN_SCRIPT
sbatch -J gl_lo_rs_SSP4_miro_6p0 $RUN_SCRIPT
sbatch -J wg_md_rs_SSP4_miro_6p0 $RUN_SCRIPT
sbatch -J gl_md_rs_SSP4_miro_6p0 $RUN_SCRIPT
sbatch -J wg_hi_rs_SSP4_miro_6p0 $RUN_SCRIPT
sbatch -J gl_hi_rs_SSP4_miro_6p0 $RUN_SCRIPT
sbatch -J wg_lo_rs_SSP5_miro_6p0 $RUN_SCRIPT
sbatch -J gl_lo_rs_SSP5_miro_6p0 $RUN_SCRIPT
sbatch -J wg_md_rs_SSP5_miro_6p0 $RUN_SCRIPT
sbatch -J gl_md_rs_SSP5_miro_6p0 $RUN_SCRIPT
sbatch -J wg_hi_rs_SSP5_miro_6p0 $RUN_SCRIPT
sbatch -J gl_hi_rs_SSP5_miro_6p0 $RUN_SCRIPT
sbatch -J wg_lo_rs_SSP1_nrsm_6p0 $RUN_SCRIPT
sbatch -J gl_lo_rs_SSP1_nrsm_6p0 $RUN_SCRIPT
sbatch -J wg_md_rs_SSP1_nrsm_6p0 $RUN_SCRIPT
sbatch -J gl_md_rs_SSP1_nrsm_6p0 $RUN_SCRIPT
sbatch -J wg_hi_rs_SSP1_nrsm_6p0 $RUN_SCRIPT
sbatch -J gl_hi_rs_SSP1_nrsm_6p0 $RUN_SCRIPT
sbatch -J wg_lo_rs_SSP2_nrsm_6p0 $RUN_SCRIPT
sbatch -J gl_lo_rs_SSP2_nrsm_6p0 $RUN_SCRIPT
sbatch -J wg_md_rs_SSP2_nrsm_6p0 $RUN_SCRIPT
sbatch -J gl_md_rs_SSP2_nrsm_6p0 $RUN_SCRIPT
sbatch -J wg_hi_rs_SSP2_nrsm_6p0 $RUN_SCRIPT
sbatch -J gl_hi_rs_SSP2_nrsm_6p0 $RUN_SCRIPT
sbatch -J wg_lo_rs_SSP3_nrsm_6p0 $RUN_SCRIPT
sbatch -J gl_lo_rs_SSP3_nrsm_6p0 $RUN_SCRIPT
sbatch -J wg_md_rs_SSP3_nrsm_6p0 $RUN_SCRIPT
sbatch -J gl_md_rs_SSP3_nrsm_6p0 $RUN_SCRIPT
sbatch -J wg_hi_rs_SSP3_nrsm_6p0 $RUN_SCRIPT
sbatch -J gl_hi_rs_SSP3_nrsm_6p0 $RUN_SCRIPT
sbatch -J wg_lo_rs_SSP4_nrsm_6p0 $RUN_SCRIPT
sbatch -J gl_lo_rs_SSP4_nrsm_6p0 $RUN_SCRIPT
sbatch -J wg_md_rs_SSP4_nrsm_6p0 $RUN_SCRIPT
sbatch -J gl_md_rs_SSP4_nrsm_6p0 $RUN_SCRIPT
sbatch -J wg_hi_rs_SSP4_nrsm_6p0 $RUN_SCRIPT
sbatch -J gl_hi_rs_SSP4_nrsm_6p0 $RUN_SCRIPT
sbatch -J wg_lo_rs_SSP5_nrsm_6p0 $RUN_SCRIPT
sbatch -J gl_lo_rs_SSP5_nrsm_6p0 $RUN_SCRIPT
sbatch -J wg_md_rs_SSP5_nrsm_6p0 $RUN_SCRIPT
sbatch -J gl_md_rs_SSP5_nrsm_6p0 $RUN_SCRIPT
sbatch -J wg_hi_rs_SSP5_nrsm_6p0 $RUN_SCRIPT
sbatch -J gl_hi_rs_SSP5_nrsm_6p0 $RUN_SCRIPT
sbatch -J wg_lo_rs_SSP5_hadg_8p5 $RUN_SCRIPT
sbatch -J gl_lo_rs_SSP5_hadg_8p5 $RUN_SCRIPT
sbatch -J wg_md_rs_SSP5_hadg_8p5 $RUN_SCRIPT
sbatch -J gl_md_rs_SSP5_hadg_8p5 $RUN_SCRIPT
sbatch -J wg_hi_rs_SSP5_hadg_8p5 $RUN_SCRIPT
sbatch -J gl_hi_rs_SSP5_hadg_8p5 $RUN_SCRIPT
sbatch -J wg_lo_rs_SSP5_miro_8p5 $RUN_SCRIPT
sbatch -J gl_lo_rs_SSP5_miro_8p5 $RUN_SCRIPT
sbatch -J wg_md_rs_SSP5_miro_8p5 $RUN_SCRIPT
sbatch -J gl_md_rs_SSP5_miro_8p5 $RUN_SCRIPT
sbatch -J wg_hi_rs_SSP5_miro_8p5 $RUN_SCRIPT
sbatch -J gl_hi_rs_SSP5_miro_8p5 $RUN_SCRIPT
sbatch -J wg_lo_rs_SSP5_nrsm_8p5 $RUN_SCRIPT
sbatch -J gl_lo_rs_SSP5_nrsm_8p5 $RUN_SCRIPT
sbatch -J wg_md_rs_SSP5_nrsm_8p5 $RUN_SCRIPT
sbatch -J gl_md_rs_SSP5_nrsm_8p5 $RUN_SCRIPT
sbatch -J wg_hi_rs_SSP5_nrsm_8p5 $RUN_SCRIPT
sbatch -J gl_hi_rs_SSP5_nrsm_8p5 $RUN_SCRIPT
